name: ssyoo
favicon: null
layout_spectrum: 0.38289713952690363
typography_spectrum: 0.6871650386601686
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6601386377587914
  lightness: 0.6690991560462862
  saturation: 0.6099957292899489
  rhythmicContrast: 0.4488862375728786
purpose: []
